### ISSUE TITLE
Render Error

### ISSUE THREAD

**Issue by polysa** [LRvdLinden/find_my_dd_addon#2]
For some reason your addon renders like this in desktop. 

Home Assistant 2021.12.1
Dwains Dashboard 2.0.5

![Screenshot 2021-12-17 115751](https://user-images.githubusercontent.com/8338620/146526409-c926f5c3-1499-4520-b5ee-3f17fb68b192.png)

Regards
Polys

**Comment by RoscoA** [comment]
This is the same issue I am having. Just installed myself.

**Comment by Hessie** [comment]
Same here

**Comment by lars-dev** [comment]
same here. 
Home Assistant 2022.2.0
Dwains Dashboard 2.0.5

**Comment by LRvdLinden** [comment]
Yeah this is a bug needs to be fixed in next version. In the mean time to fix it by hand yourself:
Add:

items_classes: 'col-xs-12 col-sm-12 col-md-12 col-lg-12'

below

- type: custom:dwains-flexbox-card

in rooms/room/addon.yaml and 04.more_page_addons.yaml
